# Signatories

Josiah Perry (Infrastructure Steering Committee member) has acknowledged the project idea and even [donated for it](buymeacoffee.com/patrickschratz/c/12848930).

Sharing the project in the `rstats` subreddit resulted [in some very positive reactions](https://www.reddit.com/r/rstats/comments/1iq7isu/package_binaries_for_arm64_and_alpine/).
(As my social media accounts are not having the greatest reach and Twitter/X is basically dead, the reactions there were limited.)

A [blog post](https://www.devxy.io/blog/cran-r-package-binaries-launch/) on devXY's website has also been shared in rweekly in December 2024.

A variety of business clients of mine have shared their enthuisiams with me personally, hoping to see a positive development of the overall project idea.

## Project team

Patrick Schratz, CEO devXY. 

Over a decade of experience with R, combined with a PhD in applied machine learning and a background in DevOps engineering. Specialized in designing and deploying R-centric data science environments for enterprise teams. Brings strong expertise in cloud infrastructure, UNIX system administration, and optimizing R for high-performance use cases.

## Contributors

None right now.
