on:
  push:
    branches: [main, master]

name: publish-proposal

permissions: 
    contents: write
    pages: write

jobs:
  render-proposal:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install rsvg
        run: sudo apt-get update && sudo apt-get install -y librsvg2-bin

      - name: Render and publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: "isc-proposal.qmd"